export { default as MainPage } from './main-page'
export { default as LoginPage } from './login'
export { default as RegisterPage } from './register'
export { default as ForgotPasswordPage } from './forgot-password'
export { default as ResetPasswordPage } from './reset-password'
export { default as ProfilePage } from './profile'
export { default as NotFound404 } from './not-found-404'