export const ADD_INGREDIENT:'ADD_INGREDIENT' = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT:'REMOVE_INGREDIENT' = 'REMOVE_INGREDIENT'
export const UPDATE_CART:'UPDATE_CART' = 'UPDATE_CART'
export const DROP_CART:'DROP_CART' = 'DROP_CART'